name: car-spare-parts
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Copy file via SSH password
        uses: appleboy/scp-action@v1
        with:
         host: ${{secrets.EC2_HOST}}
         username: ${{secrets.EC2_USERNAME}}
         key: ${{secrets.SSH_KEY}}
         port: 22
         source: "."
         target: "/var/www/html/"
        
